### ISSUE TITLE
Create lib

### ISSUE THREAD

**Issue by tcelestino** [elo7/validate-amd#1]
👍   @tisvasconcelos 

This lib is using to send error messages in the form.

https://elo7ole.atlassian.net/browse/EM-108156

**Comment by AlineLee** [comment]
The methods: 'submitOnChange', 'submitOnBlur', 'focus', should exist only in the form-amd library.

**Comment by AlineLee** [comment]
There is no .travis.yml (Like this: https://github.com/elo7/doc-amd/blob/master/.travis.yml)

**Comment by tisvasconcelos** [comment]
Dos not have a minified file

**Comment by tisvasconcelos** [comment]
The example its wrong, should be `errors = validate.validateForm('#form');`:

```js
define(['validate'], function(Validate) {
  var validate = new Validate(),
      errorMessages = validate.validateForm('#form');

  errors.forEach(function(error) {
    if (error.messages) {
      // executes when there are errors
    }
  });
});
```

**Comment by tisvasconcelos** [comment]
This is wrong to, should be `if (errorMessage.message) {`:

define(['validate'], function(Validate) {
  var validate = new Validate(),
      errorMessage = validate.validateField($('input[name=example1]'));

  if (errorMessage.messages) {
    // executes when there are errors
  }
});

**Comment by tisvasconcelos** [comment]
This is wrong to, shoud be `new Validate` and `validate.validateForm`:

```js
  var validate = new Form({ messages: custom_messages }),
      errors = validate.validate('#form');

      errors.forEach(function(error) {
        if (error.messages) {
         // executes when there are errors
        }
      });
```

**Comment by tisvasconcelos** [comment]
In the sample where you explain how to override the default messages the *url* its missing

**Comment by tisvasconcelos** [comment]
Wrong comment in `validate.js`:

```js
 * Usage example:
 * 	form.validate(<FORM_ELEMENT>);
```

**Comment by tisvasconcelos** [comment]
In the test file, I think this should be testing the `var $field = $('input[name=test2]');` and not the test1 input:

```js
it('should not return a message when the field is not of type email and is filled with an invalid email', function() {
  var $field = $('input[name=test1]');
  $field.val('notanemail');
  var formMessage = validate.validateField($field);
  expect(formMessage).to.eql({ field: $field });
});
```

**Comment by tisvasconcelos** [comment]
In the test `should return message when the select is required and value is empty` and `should not return message when the select is required and value is not empty`, do you need to create the `validate` variable again?

**Comment by tisvasconcelos** [comment]
The test html has some tags unused like `<form id="submitOnChange" action="#">`, `<form id="submitOnBlur" action="#">`, `<label id='labelAppendMessage'>`, `<div id="form-shadow-root"></div>` and `<form id="formSucess" action="#">`

**Comment by tisvasconcelos** [comment]
In the test `should error custom message for all elements` there is an unused variable `called` and some inputs like $min, $max and $patternRequired should not your values have changed to ensure the integrity of the test?

**Comment by tisvasconcelos** [comment]
How about to change this comment:

```js
/**
 * Form.
 *
 * Lib to help form manipulations
 *
 */
```

to:

/**
 * Validate.
 *
 * Lib to help form validate
 *
 */
```

**Comment by tisvasconcelos** [comment]
Its broken: https://travis-ci.org/elo7/validate-amd
